### PR TITLE
Add S3 docs in "Cloud Management"

### LINKED ISSUE #62: Add Android S3 docs in "Cloud Management"
Personally, I had no clue what you mean by "endpoint", tried S3 URLs first (particularly because I got to the form via "add existing vault" - I thought you might mean the vault URL) and only after a few trial & error attempts, I figured out that you mean `s3.<region>.amazonaws.com` (at least in case of not using a reseller).

Which is why I think it would be important to add. And I would be happy to work on it.

### PR DESCRIPTION
**Pull request by s-h-a-d-o-w**
Fixes #62

### CODE REVIEW

**Comment by s-h-a-d-o-w** [comment]
About the code rabbit suggestions:
- IAM user: At least to me, it seems excessive to mention that, since people familiar with AWS are already aware of this and for those who aren't quite as tech-savy and just use S3 for Cryptomator, I'm not confident that it's justified to make them jump through the hoop of dealing with user/permissions management.
- Regions: Overlay verbose. It should be obvious to anybody that `<region>` refers to the region that the bucket is in, particularly since there is also a `region` form field.

**Review by SailReal — APPROVED** [review]
Thank you very much for this PR :green_heart:

I'm merging this now but it would be awesome if you could sign your commits in the future https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by s-h-a-d-o-w** [comment]
You're very welcome!

> I'm merging this now but it would be awesome if you could sign your commits in the future

In the many years that I've been here, this is the first time that this has come up, so I would recommend mentioning it here: https://github.com/cryptomator/docs?tab=readme-ov-file#steps-to-contribute

**Comment by SailReal** [comment]
Good point, will add it :+1:

**Pull request merged**
